// FDE Graph Workbench palette (static, no secrets).
import type { PaletteItem } from './types.js';

export const GRAPH_PALETTE: readonly PaletteItem[] = [
  {
    kind: 'control.start',
    group: 'control',
    label: 'Start',
    description: 'Explicit graph entry',
    langflowNative: true,
  },
  {
    kind: 'control.end',
    group: 'control',
    label: 'End',
    description: 'Explicit graph exit',
    langflowNative: true,
  },
  {
    kind: 'input',
    group: 'input_output',
    label: 'Input',
    description: 'Chat/text input (native → ChatInput)',
    langflowNative: true,
  },
  {
    kind: 'output',
    group: 'input_output',
    label: 'Output',
    description: 'Chat/text output (native → ChatOutput)',
    langflowNative: true,
  },
  {
    kind: 'gateway.classify',
    group: 'reasoning',
    label: 'Classify',
    description: 'AIOS model-gateway classify (not native Langflow)',
    langflowNative: false,
  },
  {
    kind: 'gateway.summarize',
    group: 'reasoning',
    label: 'Summarize',
    description: 'AIOS model-gateway summarize (not native Langflow)',
    langflowNative: false,
  },
  {
    kind: 'gateway.verify',
    group: 'reasoning',
    label: 'Verify',
    description: 'AIOS verify step (not native Langflow)',
    langflowNative: false,
  },
  {
    kind: 'tool.read',
    group: 'tool',
    label: 'Read tool',
    description: 'AIOS MCP read capability (not native Langflow)',
    langflowNative: false,
  },
  {
    kind: 'tool.gated',
    group: 'tool',
    label: 'Gated tool',
    description: 'Write/side-effect tool; requires approval on every path',
    langflowNative: false,
  },
  {
    kind: 'approval.checkpoint',
    group: 'governance',
    label: 'Approval checkpoint',
    description: 'AIOS HITL authority (never Langflow Human Input)',
    langflowNative: false,
  },
  {
    kind: 'control.condition',
    group: 'control',
    label: 'Condition',
    description: 'Declarative branch (native → ConditionalRouter when supported)',
    langflowNative: true,
  },
  {
    kind: 'control.parallel',
    group: 'control',
    label: 'Parallel',
    description: 'Fan-out branches (AIOS control; not native yet)',
    langflowNative: false,
  },
  {
    kind: 'control.join',
    group: 'control',
    label: 'Join',
    description: 'Join parallel branches (AIOS control; not native yet)',
    langflowNative: false,
  },
  {
    kind: 'control.loop',
    group: 'control',
    label: 'Loop',
    description: 'Bounded loop (requires loop edge maxTraversals)',
    langflowNative: false,
  },
  {
    kind: 'control.failure',
    group: 'control',
    label: 'Failure',
    description: 'Failure terminal',
    langflowNative: false,
  },
  {
    kind: 'subgraph',
    group: 'composition',
    label: 'Subgraph',
    description: 'Immutable artifact-bound subgraph (native → SubFlow)',
    langflowNative: true,
  },
] as const;
