// Provision a least-privilege local account for the AIOS Agent Builder MCP.
//
// The generated password is written only to aios-mcp/.env (mode 0600) and is
// never printed. Re-running rotates the dedicated account password, revokes its
// existing sessions, and rewrites the local MCP environment atomically.
import { chmod, mkdir, rename, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { ulid } from 'ulid';
import { hashPassword } from '../lib/auth.js';
import { audit } from '../lib/audit.js';
import { randomToken } from '../lib/crypto.js';
import { prisma } from '../lib/db.js';

const serverRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const mcpRoot = path.resolve(serverRoot, '../aios-mcp');
const envPath = path.join(mcpRoot, '.env');
const tempEnvPath = `${envPath}.${process.pid}.tmp`;
const email = process.env.AIOS_MCP_PROVISION_EMAIL?.trim() || 'claude-builder@local.aios';
const displayName = process.env.AIOS_MCP_PROVISION_NAME?.trim() || 'Claude Agent Builder';
const baseUrl = process.env.AIOS_MCP_PROVISION_BASE_URL?.trim() || 'http://127.0.0.1:8700';

function dotenvLine(name: string, value: string): string {
  if (/\r|\n/.test(value)) throw new Error(`${name} must not contain a newline`);
  return `${name}=${JSON.stringify(value)}`;
}

async function main() {
  const password = randomToken(32);
  const passwordHash = await hashPassword(password);
  const existing = await prisma.user.findUnique({ where: { email } });
  const user = await prisma.$transaction(async (tx) => {
    const saved = existing
      ? await tx.user.update({
          where: { id: existing.id },
          data: {
            displayName,
            passwordHash,
            role: 'MEMBER',
            deletedAt: null,
          },
        })
      : await tx.user.create({
          data: {
            id: ulid(),
            email,
            displayName,
            passwordHash,
            role: 'MEMBER',
          },
        });

    // Password rotation invalidates every previously persisted refresh token.
    await tx.session.updateMany({
      where: { userId: saved.id, revokedAt: null },
      data: { revokedAt: new Date() },
    });
    return saved;
  });

  const env = [
    '# Generated by provision-agent-builder-mcp.ts. Keep this file private.',
    dotenvLine('AIOS_MCP_BASE_URL', baseUrl),
    dotenvLine('AIOS_MCP_EMAIL', email),
    dotenvLine('AIOS_MCP_PASSWORD', password),
    dotenvLine('AIOS_MCP_CLIENT_NAME', 'claude-agent-builder'),
    dotenvLine('AIOS_MCP_PROFILE', 'builder'),
    dotenvLine('AIOS_MCP_STATE_DIR', '~/.aios-mcp'),
    dotenvLine('AIOS_MCP_TRANSPORT', 'stdio'),
    '',
  ].join('\n');

  await mkdir(mcpRoot, { recursive: true });
  await writeFile(tempEnvPath, env, { encoding: 'utf8', mode: 0o600 });
  await chmod(tempEnvPath, 0o600);
  await rename(tempEnvPath, envPath);
  await chmod(envPath, 0o600);
  await audit(user.id, 'mcp.local_builder_account_provisioned', 'User', user.id, {
    client: 'claude-agent-builder',
    role: 'MEMBER',
    passwordRotated: existing != null,
  });

  console.log(`Provisioned ${email} as MEMBER.`);
  console.log(`Credentials were written to ${envPath} with mode 0600; the password was not printed.`);
}

main()
  .then(() => prisma.$disconnect())
  .catch(async (error) => {
    try {
      await prisma.$disconnect();
    } finally {
      console.error(error instanceof Error ? error.message : String(error));
      process.exit(1);
    }
  });
